/*

	This file is part of libigw.

	widget.c
	Widget

	Copyright (C) 2012
	Papadopoulos Nikolaos

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 3 of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General
	Public License along with this program; if not, write to the
	Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
	Boston, MA 02110-1301 USA

*/

#include <string.h>
#include "widget.h"

#ifdef __cplusplus
	extern "C" {
#endif  /* __cplusplus */

/* Presets */
#define GW_WIDGET_DEFAULT_POSITION_X	10
#define GW_WIDGET_DEFAULT_POSITION_Y	10
#define GW_WIDGET_DEFAULT_WIDTH			200
#define GW_WIDGET_DEFAULT_HEIGHT		50

#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_R 				0.f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_G 				0.f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_B 				0.f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_A 				1.0f

#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_R 				0.14f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_G 				0.14f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_B 				0.14f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_A 				1.0f

#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_R 			0.9f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_G 			0.9f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_B 			0.9f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_A 			1.0f

#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_R 			0.2f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_G 			0.2f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_B 			0.2f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_A 			1.0f

#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_R 		0.45f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_G 		0.45f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_B		0.45f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_A 		1.0f

#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_R 		0.3f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_G 		0.3f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_B 		0.3f
#define GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_A 		1.0f

#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_R 				0.6f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_G 				0.6f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_B 				0.6f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_A 				1.0f

#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_R 				0.3f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_G 				0.3f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_B 				0.3f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_A 				1.3f

#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_R 			0.83f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_G 			0.83f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_B 			0.83f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_A 			1.0f

#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_R 			0.4f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_G 			0.4f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_B 			0.4f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_A 			1.0f

#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_R 		0.2f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_G 		0.2f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_B 		0.2f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_A 		1.0f

#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_R 		0.24f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_G 		0.24f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_B 		0.27f
#define GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_A 		1.0f

#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_R 					0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_G 					0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_B 					0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_A 					1.f

#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_R 					0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_G 					0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_B 					0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_A 					1.f

#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_R 				0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_G 				0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_B 				0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_A 				1.f

#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_R 				0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_G 				0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_B 				0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_A 				1.f

#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_R 			0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_G 			0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_B			0.1f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_A 			1.f

#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_R 			0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_G 			0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_B 			0.6f
#define GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_A 			1.f

#define GW_WIDGET_DEFAULT_COLOR_TEXT_R 						0.0f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_G 						0.0f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_B 						0.0f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_A 						1.0f

#define GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_R 					0.25f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_G 					0.25f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_B 					0.25f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_A 					1.0f

#define GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_R 				1.0f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_G 				1.0f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_B 				1.0f
#define GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_A 				1.0f


void gwWidgetInit(GWwidget_t *p)
{
	if (p == NULL)
		return;

	p->position.x	= GW_WIDGET_DEFAULT_POSITION_X;
	p->position.y	= GW_WIDGET_DEFAULT_POSITION_Y;
	p->width 		= GW_WIDGET_DEFAULT_WIDTH;
	p->height 		= GW_WIDGET_DEFAULT_HEIGHT;

	p->color[GW_WIDGET_COLOR_BACKGROUND_A].r = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_R;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A].g = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_G;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A].b = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_B;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A].a = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_A;
	
	p->color[GW_WIDGET_COLOR_BACKGROUND_B].r = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_R;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B].g = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_G;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B].b = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_B;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B].a = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_A;
	
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_HOT].r = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_R;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_HOT].g = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_G;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_HOT].b = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_B;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_HOT].a = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_HOT_A;
	
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_HOT].r = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_R;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_HOT].g = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_G;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_HOT].b = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_B;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_HOT].a = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_HOT_A;
	
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_BACKGROUND_A_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_A_ACTIVE_A;
	
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_BACKGROUND_B_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_BACKGROUND_B_ACTIVE_A;

	p->color[GW_WIDGET_COLOR_FOREGROUND_A].r = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_R;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A].g = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_G;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A].b = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_B;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A].a = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_A;
	
	p->color[GW_WIDGET_COLOR_FOREGROUND_B].r = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_R;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B].g = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_G;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B].b = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_B;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B].a = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_A;
	
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_HOT].r = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_R;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_HOT].g = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_G;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_HOT].b = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_B;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_HOT].a = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_HOT_A;
	
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_HOT].r = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_R;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_HOT].g = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_G;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_HOT].b = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_B;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_HOT].a = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_HOT_A;
	
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_FOREGROUND_A_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_A_ACTIVE_A;
	
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_FOREGROUND_B_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_FOREGROUND_B_ACTIVE_A;

	p->color[GW_WIDGET_COLOR_BEVEL_A].r = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_R;
	p->color[GW_WIDGET_COLOR_BEVEL_A].g = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_G;
	p->color[GW_WIDGET_COLOR_BEVEL_A].b = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_B;
	p->color[GW_WIDGET_COLOR_BEVEL_A].a = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_A;
	
	p->color[GW_WIDGET_COLOR_BEVEL_B].r = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_R;
	p->color[GW_WIDGET_COLOR_BEVEL_B].g = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_G;
	p->color[GW_WIDGET_COLOR_BEVEL_B].b = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_B;
	p->color[GW_WIDGET_COLOR_BEVEL_B].a = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_A;
	
	p->color[GW_WIDGET_COLOR_BEVEL_A_HOT].r = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_R;
	p->color[GW_WIDGET_COLOR_BEVEL_A_HOT].g = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_G;
	p->color[GW_WIDGET_COLOR_BEVEL_A_HOT].b = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_B;
	p->color[GW_WIDGET_COLOR_BEVEL_A_HOT].a = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_HOT_A;
	
	p->color[GW_WIDGET_COLOR_BEVEL_B_HOT].r = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_R;
	p->color[GW_WIDGET_COLOR_BEVEL_B_HOT].g = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_G;
	p->color[GW_WIDGET_COLOR_BEVEL_B_HOT].b = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_B;
	p->color[GW_WIDGET_COLOR_BEVEL_B_HOT].a = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_HOT_A;
	
	p->color[GW_WIDGET_COLOR_BEVEL_A_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_BEVEL_A_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_BEVEL_A_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_BEVEL_A_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_BEVEL_A_ACTIVE_A;
	
	p->color[GW_WIDGET_COLOR_BEVEL_B_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_BEVEL_B_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_BEVEL_B_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_BEVEL_B_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_BEVEL_B_ACTIVE_A;

	p->color[GW_WIDGET_COLOR_TEXT].r = GW_WIDGET_DEFAULT_COLOR_TEXT_R;
	p->color[GW_WIDGET_COLOR_TEXT].g = GW_WIDGET_DEFAULT_COLOR_TEXT_G;
	p->color[GW_WIDGET_COLOR_TEXT].b = GW_WIDGET_DEFAULT_COLOR_TEXT_B;
	p->color[GW_WIDGET_COLOR_TEXT].a = GW_WIDGET_DEFAULT_COLOR_TEXT_A;

	p->color[GW_WIDGET_COLOR_TEXT_HOT].r = GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_R;
	p->color[GW_WIDGET_COLOR_TEXT_HOT].g = GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_G;
	p->color[GW_WIDGET_COLOR_TEXT_HOT].b = GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_B;
	p->color[GW_WIDGET_COLOR_TEXT_HOT].a = GW_WIDGET_DEFAULT_COLOR_TEXT_HOT_A;

	p->color[GW_WIDGET_COLOR_TEXT_ACTIVE].r = GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_R;
	p->color[GW_WIDGET_COLOR_TEXT_ACTIVE].g = GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_G;
	p->color[GW_WIDGET_COLOR_TEXT_ACTIVE].b = GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_B;
	p->color[GW_WIDGET_COLOR_TEXT_ACTIVE].a = GW_WIDGET_DEFAULT_COLOR_TEXT_ACTIVE_A;
}

#ifdef __cplusplus
	}   /* extern "C" */
#endif /* __cplusplus */
